### ISSUE TITLE
Gazer export on nil space fails

### ISSUE THREAD

**Issue by benpoliquin** [looker-open-source/gzr#34] opened 2019-05-29 21:37 UTC
I am trying to run `gzr space export 2 --dir .` but get the failure below. 

When I run `gzr space tree 2`, it shows:
Users
└── nil (340)
└── Person Name
...

Error Log:
```/Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:78:in `process_space': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:111:in `block in process_space'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:110:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:110:in `process_space'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:71:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/modules/session.rb:193:in `with_session'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space/export.rb:48:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/lib/gzr/commands/space.rb:76:in `export'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/gazer-0.2.13/exe/gzr:36:in `<top (required)>'
	from /usr/local/bin/gzr:22:in `load'
	from /usr/local/bin/gzr:22:in `<main>'```

**Comment by benpoliquin** [comment] 2019-05-29 21:38
I think the space name might need to be a pointer reference before it calls gsub but I am unable to test.

**Comment by sabarber-looker** [comment] 2019-08-19 19:49
It looks like:

`path = Pathname.new(space.name.gsub('/',"\u{2215}"))
`
is the culprit here.  In this case, I believe the spaces of deleted users are have a nil name, and this line does not have error handling for the nil case.  My intuition is to skip these with a conditional e.g. ```
if space.name
...
end
```

**Comment by sabarber-looker** [comment] 2019-08-19 19:58
Update, not deleted users -- these spaces appear to belong to invited users who have not yet completed registration/logged in for the first time and thus do not have a first/last name set.

**Comment by sabarber-looker** [comment] 2019-08-19 20:52
And one more nugget of info, it looks like the act of querying the user's space with the API before they are registered is what creates the problem is the first place.  To reproduce:
(1) Create new user
(2) `gzr space ls 2`
and note that the new user is not present.
(3) `gzr user ls`
and note new user's space ID
(4) `gzr space ls <num>`
where <num> is the space ID for the new user (e.g. 7)
(5) `gzr space ls 2`
and note that the new user is now present, meaning gazer will throw the nil error on gzr space export 2 until the user is registered.

**Comment by deangelo-llooker** [comment] 2019-11-19 22:36
Should be fixed in v0.2.23. Please reopen if not fixed.

**Closed by deangelo-llooker** 2019-11-19 22:36 UTC

**Comment by benpoliquin** [comment] 2019-11-19 23:52
Thank you for fixing this! @deangelo-llooker 🥇
