### ISSUE TITLE
Throwing time out error

### ISSUE THREAD

**Issue by tamalampudi** [looker-open-source/gzr#84] opened 2021-01-14 13:31 UTC
Script -1
gzr space export 1 --host='xxxxxx.com' --port='443' --client-id='xxxxxxxxxxx' --client-secret='xxxxxxxxxxx' 

Script -2 
gzr space export 1 --host='xxxxxx.com' --port='443' --client-id='xxxxxxxxxxx' --client-secret='xxxxxxxxxxx' --timeout=600

Getting the below error:

       1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': Operation timed out - SSL_connect (Faraday::TimeoutError)

 Note: Tried both the scripts , but still getting the time out error:

**Comment by KGoodacre** [comment] 2021-10-13 23:03
The issue is that we use Gazer to backup our company's spaces (Shared & Personal/Users) to a Git Repository.

We are using a cloud Looker server and every time we use the "gzr space export" command we receive a timeout error. The timeout error is thrown inconsistently; sometimes it occurs seconds after issuing the command, and sometimes it takes an hour before throwing the timeout error.

We've tried many workarounds such as: 

1. Increasing the timeout amount.
2. Increasing the timeout to a ridiculous amount 70k+.
2. Splitting the export space job into smaller sections (using the individual child space ids instead of the parent id 1 or 2).
3. Updating ruby & packages dependencies to use the latest.
4. Having several people run the command using different combinations of package versions.

Nothing seems to work, we run into the same error every time.

@drstrangelooker @ajcrutch
Could you please assist us in a workaround for this issue? It is very critical.

- [ ] Maybe assist us with a customized API request call that functions just as the "gzr space export" command. (Could you provide which Looker API calls are being used?)
- [ ] Or any workarounds to eliminate the issue.

USAGE: "gzr space export" to convert each space and it's folder structure into json files. Then we push to Git, this is done once a day for spaces 1 & 2, in order to create a backup source. --> This is done through a TeamCity build


<details>
<summary>EXAMPLE OF ERROR:</summary>

`
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect': Failed to open TCP connection to companystaging.cloud.looker.com:443 (getaddrinfo: Name or service not known) (Faraday::ConnectionFailed)
from /usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
from /usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
from /usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
from /usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
from /usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
from /usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
from /usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
from /usr/lib/ruby/2.5.0/net/http.rb:1216:in `get'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:86:in `perform_request'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:44:in `block in call'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:93:in `with_net_http_connection'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/adapter/net_http.rb:39:in `call'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/response.rb:8:in `call'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/rack_builder.rb:143:in `build_response'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/connection.rb:387:in `run_request'
from /var/lib/gems/2.5.0/gems/faraday-0.17.4/lib/faraday/connection.rb:138:in `get'
from /var/lib/gems/2.5.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
from /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client.rb:304:in `request'
from /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client.rb:96:in `get'
from /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:139:in `invoke_remote'
from /var/lib/gems/2.5.0/gems/looker-sdk-0.0.7/lib/looker-sdk/client/dynamic.rb:106:in `method_missing'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/dashboard.rb:29:in `query_dashboard'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:110:in `block in process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:109:in `each'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:109:in `process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:138:in `block in process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `each'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:138:in `block in process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `each'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:138:in `block in process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `each'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:137:in `process_space'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:81:in `block in execute'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/modules/session.rb:207:in `with_session'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space/export.rb:49:in `execute'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/lib/gzr/commands/space.rb:80:in `export'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
from /var/lib/gems/2.5.0/gems/gazer-0.2.44/exe/gzr:36:in `<top (required)>'
from /usr/local/bin/gzr:23:in `load'
from /usr/local/bin/gzr:23:in `<main>'
Process exited with code 1`

</details>

**Comment by michaelcramer** [comment] 2022-02-07 04:20
Duplicate of #97

**Closed by michaelcramer** 2022-02-07 04:20 UTC
