### ISSUE TITLE
Alerts Removed After gzr dashboard import

### ISSUE THREAD

**Issue by jasonstinnett** [looker-open-source/gzr#113] opened 2021-11-29 16:50 UTC
## Summary
We are using gazer to migrate UDDs from our QA environment to our Production environment. 

After reimporting an existing UDD into production, alerts that users had previously created in the production environment are removed. Note that this is true even if no changes were actually made to the UDD.

## Steps To Reproduce
1. Create a new alert in an existing UDD in the destination environment
2. Export from the source environment e.g. `gzr space export {source_space_id} --host={source_host} --dir=exports`
3. Import the UDD into the destination environment e.g. `gzr dashboard import {path}/{filename} {destination_space_id} --host={destination_host} --force`
4. Reload the dashboard in the destination environment.

When a user goes back into the dashboard and clicks on the bell icon to create and manage alerts, they will no longer see the alert created in step 1.

When an admin goes into Admin > Alerts & Schedules > Alerts, they will observe that the alert created and step 1 is present, however the Dashboard column (which should list the dashboard name) now says None. We have observed that the Alert Status does not immediately change from Active to Disabled, however it will eventually change to Disabled automatically.

## Expected Behavior
I was unable to find anything in the documentation that explicitly discussed alerts. However, I do see in the dashboard import  documentation that "Gazer will attempt to update an existing dashboard or look of the same name, rather than create a new dashboard or look. In this way the id, share URLs, schedules, permissions, etc. will be preserved." 

My expectation is that alerts would be preserved in this manner as well.

**Comment by tkofford-bytecode** [comment] 2022-01-13 20:15
We investigated this issue and know the root cause. The alerts are not deleted, but rather unlinked from their imported dashboard elements. The fix for this will be added to the feature backlog, as it will require an upgrade to Looker SDK v4.x.

**Closed by tkofford-bytecode** 2022-01-13 20:15 UTC
Labels: investigating

**Comment by jasonstinnett** [comment] 2022-01-14 15:21
@tkofford-bytecode thanks for the update. Have you considered updating the dashboard import documentation in the interim, to call out that alerts will be unlinked? https://github.com/looker-open-source/gzr#dashboard-import
